[[news]]
date = "2026-01"
content = "One paper accepted by **AAAI 2026**!"

[[news]]
date = "2026-01"
content = "One paper submitted to **ICML 2026**."

[[news]]
date = "2026-01"
content = "One paper submitted to **ACM MM 2026**."

[[news]]
date = "2024-06"
content = "One paper accepted by **MICCAI 2024**!"

[[news]]
date = "2024-01"
content = "Serving as a reviewer for ACM MM 2026, MICCAI 2026, and AAAI 2026."
