[[news]]
date = "2026-03"
content = "One paper submitted to **ACM MM 2026**."

[[news]]
date = "2026-01"
content = "One paper submitted to **ICML 2026**."

[[news]]
date = "2025-11"
content = "One paper accepted as **Poster** at **AAAI 2026**! 🎉"
