[[news]]
date = "2026-07"
content = "One paper accepted at **ACM MM 2026**! 🎉"

[[news]]
date = "2026-06"
content = "Led team to win **First Prize** at Sichuan Province **\"Challenge Cup\"** Competition! 🏆"

[[news]]
date = "2026-05"
content = "Two papers submitted to **NeurIPS 2026**."

[[news]]
date = "2026-05"
content = "One paper narrowly missed acceptance at **ICML 2026**."

[[news]]
date = "2026-03"
content = "One paper submitted to **ACM MM 2026**."

[[news]]
date = "2026-01"
content = "One paper submitted to **ICML 2026**."

[[news]]
date = "2025-11"
content = "One paper accepted as **Poster** at **AAAI 2026**! 🎉"
