[[news]]
date = "2026-01"
content = "一篇论文被 **AAAI 2026** 录用！"

[[news]]
date = "2026-01"
content = "一篇论文投稿至 **ICML 2026**。"

[[news]]
date = "2026-01"
content = "一篇论文投稿至 **ACM MM 2026**。"

[[news]]
date = "2024-06"
content = "一篇论文被 **MICCAI 2024** 录用！"

[[news]]
date = "2024-01"
content = "担任 ACM MM 2026、MICCAI 2026、AAAI 2026 审稿人。"
