[[news]]
date = "2026-03"
content = "一篇论文投稿至 **ACM MM 2026**。"

[[news]]
date = "2026-01"
content = "一篇论文投稿至 **ICML 2026**。"

[[news]]
date = "2025-11"
content = "一篇论文被 **AAAI 2026** 录用为 **Poster**！🎉"
